import type { Metadata } from "next";
import { LegalPage } from "@/components/seo/legal-page";

const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://study-ai-two-sable.vercel.app";

export const metadata: Metadata = {
  title: "Terms & Conditions — StudyAI",
  description:
    "The terms and conditions for using StudyAI, including acceptable use, your content, AI-generated material, and limitation of liability.",
  alternates: { canonical: "/terms" },
  openGraph: { title: "Terms & Conditions — StudyAI", url: `${baseUrl}/terms` },
};

const sections = [
  {
    heading: "Acceptance of terms",
    body: [
      "By accessing or using StudyAI, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the service.",
    ],
  },
  {
    heading: "The service",
    body: [
      "StudyAI is a free, ad-supported AI study assistant that turns uploaded documents into study tools such as notes, summaries, flashcards, quizzes, and mind maps. We may change, suspend, or discontinue any part of the service at any time.",
    ],
  },
  {
    heading: "Your account",
    body: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must be at least 13 years old to use StudyAI.",
    ],
  },
  {
    heading: "Your content",
    body: [
      "You retain ownership of the documents you upload. By uploading a document, you grant us a limited license to store, process, and transmit it solely for the purpose of providing the service to you.",
      "You confirm that you have the right to upload the content you provide and that it does not infringe the rights of others or violate the law.",
    ],
  },
  {
    heading: "Acceptable use",
    body: [
      "You agree not to misuse the service — for example, by attempting to gain unauthorized access, uploading malicious software, using the service to break the law, or interfering with other users' ability to use the service.",
    ],
  },
  {
    heading: "AI-generated content",
    body: [
      "Study tools are generated by artificial intelligence. AI output can be imperfect: it may contain errors, omissions, or inaccuracies. You should verify important information and use study tools as a supplement to, not a replacement for, your own learning and your official course materials.",
    ],
  },
  {
    heading: "Advertising",
    body: [
      "StudyAI is supported by advertising. You agree to allow the display of advertisements as part of the service.",
    ],
  },
  {
    heading: "Termination",
    body: [
      "You may stop using StudyAI at any time. We may suspend or terminate access to the service for violations of these terms or activity that threatens the security or stability of the service.",
    ],
  },
  {
    heading: "Disclaimer of warranties",
    body: [
      "The service is provided 'as is' and 'as available' without warranties of any kind, whether express or implied. We do not guarantee that the service will be uninterrupted, error-free, or that study tools will be accurate or complete.",
    ],
  },
  {
    heading: "Limitation of liability",
    body: [
      "To the maximum extent permitted by law, StudyAI and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of, or inability to use, the service.",
    ],
  },
  {
    heading: "Changes to these terms",
    body: [
      "We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the updated terms.",
    ],
  },
  {
    heading: "Contact",
    body: [
      "If you have questions about these terms, email ssearch456@gmail.com.",
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      updated="August 2026"
      sections={sections}
    />
  );
}
